spring.application.name=planillas
spring.datasource.url=jdbc:mysql://localhost:3306/planillas
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

